<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array/>
	<key>firstLineMatch</key>
	<string>^\\begin(\[.*\])?\{tikzpicture\}</string>
	<key>foldingStartMarker</key>
	<string>\\begin\{.*\}|%.*\(fold\)\s*$</string>
	<key>foldingStopMarker</key>
	<string>\\end\{.*\}|%.*\(end\)\s*$</string>
	<key>name</key>
	<string>TikZ</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>\s*((\\)(draw|node|path))</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.draw.latex.tikz</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.function.latex.tikz</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.terminator.latex.tikz</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.draw.latex.tikz</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#options</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#points</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tex</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>text.tex.latex</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>options</key>
		<dict>
			<key>begin</key>
			<string>(\[)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.arguments.begin.latex.tikz</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.arguments.end.latex.tikz</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.arguments.optional.latex.tikz</string>
		</dict>
		<key>points</key>
		<dict>
			<key>begin</key>
			<string>(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.arguments.begin.latex.tikz</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.arguments.end.latex.tikz</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.point.latex.tikz</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[a-zA-Z0-9 ]*</string>
					<key>name</key>
					<string>entity.name.node.latex.tikz</string>
				</dict>
			</array>
		</dict>
		<key>tex</key>
		<dict>
			<key>begin</key>
			<string>(\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.latex.tikz</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.latex.tikz</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.other.tex.latex.tikz</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.tex.latex</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.tex.latex.tikz</string>
	<key>uuid</key>
	<string>3F55FDC0-E5A1-4406-A8FB-73CA60D7C80D</string>
</dict>
</plist>
